module.exports = {
  config: {
    backgroundColor: "#292d3e",
    bell: "SOUND",
    borderColor: "#292d3e",
    colors: {
      black: "#000000",
      blue: "#82aaff",
      cyan: "#89ddff",
      green: "#c3e88d",
      magenta: "#c792ea",
      red: "#ff5370",
      white: "#ffffff",
      yellow: "#ffcb6b",
      lightBlack: "#676e95",
      lightBlue: "#82aaff",
      lightCyan: "#89ddff",
      lightGreen: "#c3e88d",
      lightMagenta: "#c792ea",
      lightRed: "#ff5370",
      lightWhite: "#ffffff",
      lightYellow: "#ffcb6b"
    },
    copyOnSelect: false,
    css: "",
    cursorAccentColor: "#292d3e",
    cursorBlink: false,
    cursorColor: "#ffcc00",
    cursorShape: "BLOCK",
    defaultSSHApp: true,
    env: {},
    fontFamily: '"FuraCode Nerd Font", monospace',
    fontSize: 12,
    fontWeight: 500,
    fontWeightBold: 700,
    foregroundColor: "#a6accd",
    letterSpacing: 0,
    lineHeight: 1,
    macOptionSelectionMode: "vertical",
    padding: "12px 14px",
    quickEdit: false,
    selectionColor: "#a6accd",
    shell: "",
    shellArgs: ["--login"],
    showHamburgerMenu: "",
    showWindowControls: "",
    termCSS: "",
    updateChannel: "canary",
    webGLRenderer: true
  },
  keymaps: {},
  localPlugins: [],
  plugins: []
};
